{% include 'header.phtml'%}

	<div class="row contato">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <div class="formulario">
            	<div class="info-form">
            		<h1>Solicite um Orçamento</h1>
            		<p>
            			Solicite um orçamento, e responderemos o mais rapido possivel.
            		</p>
            	</div>
            	<div id="mensagem" class=""></div>
                <form id="email-formulario" method="post">
                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nome">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="subject">Assunto</label>
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Assunto">
                    </div>
                    <div class="form-group">
	                    <label for="subject">Mensagem</label>
                        <textarea class="form-control" rows="3" name="message" placeholder="Mensagem"></textarea>
                    </div>
                    <button type="submit" class="button button-default">Enviar</button>
                </form>
            </div>
        </div>
    </div>

{% include 'footer.phtml'%}