		<section class="footer row">
			<article>
				<div class="foto">
					<h1>Foto Gabriella Aguillar</h1>
				</div>
				<div class="minibiografia">
					<h2>Sobre Gabriella Aguillar</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex quas cumque, doloremque provident vitae esse a dolores nihil optio laborum hic tempore quidem, beatae qui quaerat modi voluptatem eaque at?</p>
				</div>
			</article>
			<article>
				<div class="info">
					<h2>Nossas Midias Sociais</h2>
					<p class="facebook"><i class="fa fa-facebook-square"></i>Facebook</p>
						<div class="fb-like"
							data-href="https://www.facebook.com/AguillarArts/"
							data-layout="button_count"
							data-action="like"
							data-size="small"
							data-show-faces="false"
							data-share="true">
						</div>
				</div>


				<div class="fb-page"
				 data-href="https://www.facebook.com/aguillararts"
				 data-tabs="timeline"
				 data-width="300"
				 data-height="400"
				 data-small-header="false"
				 data-adapt-container-width="false"
				 data-hide-cover="false"
				 data-show-facepile="true">
					 <blockquote cite="https://www.facebook.com/aguillararts"
					 class="fb-xfbml-parse-ignore">
						 <a href="https://www.facebook.com/aguillararts">
						 	Aguillar Arts
						 </a>
					 </blockquote>
				 </div>
			</article>
		</section>
    </section>
    {% for js in assets.js %}
<script type="text/javascript" src="./Public/Assets/dist/js/{{js}}"></script>
    {% endfor %}
</body>
</html>