		<section class="footer row" id="footer">
			<article>
				<div class="foto">
					<h1>Foto Gabriella Aguillar</h1>
				</div>
				<div class="minibiografia">
					<h2>Sobre Gabriella Aguillar</h2>
					<p>
						Formada em Publicidade e Propaganda pela Unaerp, inseriu-se no mercado de trabalho muito jovem em grandes empresas como Nestlé, Itau e posteriormente Ambev. Decidiu então reunir todo o conhecimento adquirido para iniciar no mercado publicitário focando nas pequenas empresas. 

					</p>
				</div>
			</article>
			<article>
				<div class="info">
					<h2>Nossas Midias Sociais</h2>
					<p class="facebook"><i class="fa fa-facebook-square"></i>Facebook</p>
						<div class="fb-like"
							data-href="https://www.facebook.com/AguillarArts/"
							data-layout="button_count"
							data-action="like"
							data-size="small"
							data-show-faces="false"
							data-share="true">
						</div>
				</div>


				<div class="fb-page"
				 data-href="https://www.facebook.com/aguillararts"
				 data-tabs="timeline"
				 data-width="300"
				 data-height="400"
				 data-small-header="false"
				 data-adapt-container-width="false"
				 data-hide-cover="false"
				 data-show-facepile="true">
					 <blockquote cite="https://www.facebook.com/aguillararts"
					 class="fb-xfbml-parse-ignore">
						 <a href="https://www.facebook.com/aguillararts">
						 	Aguillar Arts
						 </a>
					 </blockquote>
				 </div>
			</article>
		</section>
    </section>
    {% for js in assets.js %}
<script type="text/javascript" src="./Public/Assets/dist/js/{{js}}" defer></script>
    {% endfor %}

	<script type="application/ld+json" async>
	{
	  "@context": "http://schema.org",
	  "@type": "Organization",
	  "address": {
	    "@type": "PostalAddress",
	    "addressLocality": "São Paulo, Brasil",
	    "postalCode": "14030-440",
	    "streetAddress": "Rua Dr. João Guião, 266 - Vila Virginia, Ribeirão Preto"
	  },
	  "email": "contato@aguillararts.com.br",
	  "founder": [
	    {
	      "@type": "Person",
	      "name": "Rafael Dimas",
	      "jobTitle": "Desenvolvedor Web",
	      "sameAs": "https://www.facebook.com/rafaelhodimas"
	    },
	    {
	      "@type": "Person",
	      "name": "Gabriella Aguillar",
	      "jobTitle": "Publicitária",
	      "sameAs": "https://www.facebook.com/gabriella.aguillar"
	    }
	  ],
	  "name": "Aguillar Arts",
	  "telephone": "(16) 98824-3540",
	  "url": "http://www.aguillararts.com.br/",
	  "logo": "http://www.aguillararts.com.br/Public/Assets/dist/css/img/logo/logo-menu.png",
	  "sameAs": [
	    "https://www.facebook.com/AguillarArts/",
	    "https://plus.google.com/100860257454348727280?hl=pt-PT"
	  ]
	}
	</script>
	<script async>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-88061132-1', 'auto');
	  ga('send', 'pageview');

	</script>
</body>
</html>