		<section class="footer row">
			<article class="col-xs-12 col-md-5">
				
			</article>
			<article class="col-xs-12 col-md-5 col-md-offset-1">
				<div class="face">
					<div class="fb-page"
						data-href="https://www.facebook.com/AguillarArts/"
						data-tabs="timeline"
						data-width="290"
						data-height="300"
						data-small-header="true"
						data-adapt-container-width="true"
						data-hide-cover="false"
						data-show-facepile="true">
						<blockquote cite="https://www.facebook.com/AguillarArts/" class="fb-xfbml-parse-ignore">
							<a href="https://www.facebook.com/AguillarArts/">Aguillar Arts</a>
						</blockquote>
					</div>
				</div>
			</article>
		</section>
    </section>
    {% for js in assets.js %}
<script type="text/javascript" src="./Public/Assets/dist/js/{{js}}"></script>
    {% endfor %}
</body>
</html>