<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aguillar Arts - {{title}} </title>
    <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{description}}">
    <meta name="robots" content="index, follow">
    <meta name="google-site-verification" content="OgcksyYksM2j-gWE-99LGtLuZ2o5oiCcF8zU7TGUxyY" />
    <link rel="icon" href="./Public/Assets/dist/css/img/icons/favicon.png" />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:400,700,300'>
    <link rel="stylesheet" href="./Public/Assets/dist/css/font-awesome/css/font-awesome.min.css">
    {% for css in assets.css %}
<link rel="stylesheet" href="./Public/Assets/dist/css/{{css}}">
    {% endfor %}
</head>
<body>
<div id="fb-root"></div>
    <section>
        <header class="row">
            <a href="#" class="active-menu"><i class="fa fa-bars" aria-hidden="true"></i></a>
            <nav class="menu-toggle">
                <ul>
                    <a href="#" class="disable-menu"><i class="fa fa-times" aria-hidden="true"></i></a>
                    <li><a href="/" class="not" title="Pagina Inicial - Aguillar Arts"><img src="./Public/Assets/dist/css/img/logo/logo-menu.png" alt="Logo - Aguillar Arts"></a></li>
                    <li><a href="/sobre" title="Pagina Sobre - Aguillar Arts">Sobre</a></li>
                    <li><a href="/servicos" title="Pagina Serviços - Aguillar Arts">Serviços</a></li>
                    <li><a href="/portfolio" title="Pagina Portfólio - Aguillar Arts">Portfólio</a></li>
                    <li><a href="/contato" title="Pagina Contato - Aguillar Arts">Contato</a></li>
                </ul>
            </nav>
            <nav class="menu-desktop col-xs-12 col-md-12">
                <ul>
                    <li><a href="/sobre" title="Pagina Sobre - Aguillar Arts">Sobre</a></li>
                    <li><a href="/servicos" title="Pagina Serviços - Aguillar Arts">Serviços</a></li>
                    <li><a href="/" class="not" title="Pagina Inicial - Aguillar Arts"><img src="./Public/Assets/dist/css/img/logo/logo-menu.png" alt="Logo - Aguillar Arts"></a></li>
                    <li><a href="/portfolio" title="Pagina Portfólio - Aguillar Arts">Portfólio</a></li>
                    <li><a href="/contato" title="Pagina Contato - Aguillar Arts">Contato</a></li>
                </ul>
            </nav>
            <div id="owl-demo" class="owl-carousel owl-theme">
                <a href="/">
                    <div class="item"><img src="./Public/Assets/dist/css/img/slide/promocao-facebook-email.jpg" alt="Aguillar Arts, qualidade com preço baixo."></div>
                </a>
                <a href="/">
                    <div class="item"><img src="./Public/Assets/dist/css/img/slide/nossas-redes-sociais.jpg" alt="Nossas redes sociais, curta, compartilha, e nos siga para novidades."></div>
                </a>
                <a href="#footer">
                    <div class="item"><img src="./Public/Assets/dist/css/img/slide/promocao-facebook-email.jpg" alt="Promoção Gerenciamento de Facebook + Email Marketing por apenas R$ 400,00, imperdível!!"></div>
                </a>
            </div>
        </header>
