<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aguillar Arts - {{title}} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./Public/Assets/dist/css/img/icons/favicon.png" />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:400,700,300'>
    <link rel="stylesheet" href="./Public/Assets/dist/css/font-awesome/css/font-awesome.min.css">
    {% for css in assets.css %}
<link rel="stylesheet" href="./Public/Assets/dist/css/{{css}}">
    {% endfor %}
</head>
<body>
<div id="fb-root"></div>
    <section>
        <header class="row">
            <nav class="col-xs-12 col-md-12">
                <ul>
                    <li><a href="/sobre">Sobre</a></li>
                    <li><a href="/servicos">Serviços</a></li>
                    <li><a href="/" class="not"><img src="./Public/Assets/dist/css/img/logo/logo-menu.png" alt=""></a></li>
                    <li><a href="/portfolio">Portfolio</a></li>
                    <li><a href="/contato">Contato</a></li>
                </ul>
            </nav>
            <div id="owl-demo" class="owl-carousel owl-theme">
              <div class="item"><img src="./Public/Assets/dist/css/img/background/servicos.jpg" alt=""></div>
              <div class="item"><img src="./Public/Assets/dist/css/img/background/servicos.jpg" alt=""></div>
              <div class="item"><img src="./Public/Assets/dist/css/img/background/servicos.jpg" alt=""></div>
            </div>
        </header>
