<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Aguillar Arts - </title>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:400,700,300'>
    <link rel="stylesheet" href="./Public/Assets/dist/css/font-awesome/css/font-awesome.min.css">
    {% for css in assets.css %}
<link rel="stylesheet" href="./Public/Assets/dist/css/{{css}}">
    {% endfor %}
</head>
<body>
    <section>
        <header class="row">
            <nav class="col-xs-12 col-md-12">
                <ul>
                    <li><a href="/">Inicio</a></li>
                    <li><a href="/sobre">Sobre</a></li>
                    <li><a href="/" class="not"><img src="./Public/Assets/dist/css/img/logo.jpg" width="100px" height="100%" alt=""></a></li>
                    <li><a href="/portfolio">Portfolio</a></li>
                    <li><a href="/contato">Contato</a></li>
                </ul>
            </nav>
            <div id="owl-demo" class="owl-carousel owl-theme">
              <div class="item"><img src="http://lorempixel.com/1336/500/technics/" alt="The Last of us"></div>
              <div class="item"><img src="http://lorempixel.com/1337/500/technics/" alt="GTA V"></div>
              <div class="item"><img src="http://lorempixel.com/1335/500/technics/" alt="Mirror Edge"></div>
            </div>
        </header>
