{% include 'header.phtml'%}
        <section class="sobre row">
            <article class="col-xs-12 col-md-6">
                <h1>Sobre a Aguillar Arts</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                </p>
            </article>
        </section>
        <section class="servicos row container">
            <div class="menu">
                <ul>
                    <li class="ativo" id="producao"><img src="./Public/Assets/dist/css/img/icons/producao.png" alt=""></l>
                    <li class="disable" id="email"><img src="./Public/Assets/dist/css/img/icons/email.png" alt=""></l>
                    <li class="disable" id="midia"><img src="./Public/Assets/dist/css/img/icons/midia.png" alt=""></l>
                    <li class="disable" id="criacao"><img src="./Public/Assets/dist/css/img/icons/criacao.png" alt=""></l>
                    <li class="disable" id="visual"><img src="./Public/Assets/dist/css/img/icons/visual.png" alt=""></l>
                    <li class="disable" id="offiline"><img src="./Public/Assets/dist/css/img/icons/offiline.png" alt=""></li>
                </ul>
            </div>
            <div class="texto producao">
                <h2>Produção de Campanhas</h2>
                <p>
                    Fazemos toda a produção da sua campanha desde a produção de fotos, vídeos e materiais de áudio a edição e finalização das peças. Organizamos eventos corporativos e coquetéis de divulgação.
                </p>
            </div>
            <div class="texto email">
                <h2>Email Marketing</h2>
                <p>
                    As melhores soluções para criação do seu email Marketing com vários planos de envios e geração automática do seu email com template pré-definido.
                </p>
            </div>
            <div class="texto midia">
                <h2>Mídias Sociais</h2>
                <p>
                    Através das mídias sociais podemos aumentar a visibilidade de sua marca, consciência sobre seus produtos e serviços e consequentemente gerar mais vendas e aumentar a retenção de clientes. Fazemos a criação de conteúdo, monitoramento, promoções e campanhas.
                </p>
            </div>
            <div class="texto criacao">
                <h2>Criação de Site</h2>
                <p>
                    Desenvolvemos websites personalizados de acordo com as necessidades de cada cliente. Criamos seu website com qualidade levando em conta a otimização do SEO de cada página, para isso trabalhamos o design em perfeita harmonia com a programação e a arquitetura de informações para a usabilidade do cliente.
                </p>
            </div>
            <div class="texto visual">
                <h2>Identidade Visual</h2>
                <p>
                    Para criar ou modernizar a identidade visual de sua empresa nós desenvolvemos e modernizamos logotipos, logomarcas e símbolos além de criar todo o material institucional do dia a dia. Isso inclui cartões de visita, timbrados, envelopes, pastas, receituários, mascotes, sinalização interna, adesivo de veículos, placas,  wallpapers de computador, assinatura digital para e-mails, crachás e muito mais.
                </p>
            </div>
            <div class="texto offiline">
                <h2>Mídia Offiline</h2>
                <p>
                    Catálogos, folders, folhetos, malas-direta, cartazes, placas, banners, panfletos, outdoors, busdoors, jornais, livros, revistas, apostilas, cartões postais, calendários, certificados. Fazemos desde a arte inicial até a impressão para melhor atende-los!
                </p>
            </div>
        </section>
        <section class="blog row">
            <h1>Em construção...</h1>
            <p>Em breve muitos artigos para melhorar a projeção da sua empresa na web e nos meios em que atua.</p>
        </section>
        <section class="contato row">
            <div class="container">
                <h1><i class="fa fa-comments-o" aria-hidden="true"></i>Contato</h1>

                <article class="col-xs-12 col-md-3 telefone">

                    <h2><i class="fa fa-phone-square" aria-hidden="true"></i>Telefones</h2>

                    <p>Entre em contato, vamos achar a melhor solução para o seu problema.</p>

                    <a href="tel:1639196840"  target="_blank"><i class="fa fa-phone" aria-hidden="true"></i> (16) 39196840</a><br>                    

                    <a href="tel:16988243540"  target="_blank"><i class="fa fa-mobile" aria-hidden="true"></i> (16) 98824-3540</a><br>

                    <a href="intent://send/16988243540#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end" target="_blank"><i class="fa fa-whatsapp" aria-hidden="true"></i> (16) 98824-3540</a><br>

                </article>

                <article class="col-xs-12 col-md-3 col-md-offset-1 email">

                    <h2><i class="fa fa-envelope" aria-hidden="true"></i>E-mail</h2>

                    <p>Nos envie um email com as suas duvidas, vamos adorar esclarecer. Aceitamos <b>Orçamento</b> tambem.</p>

                    <a href="/contato/">Contato</a>

                </article>

                <article class="col-xs-12 col-md-3 col-md-offset-1 atendimento">
                    <h2><i class="fa fa-hourglass-half" aria-hidden="true"></i>Atendimento</h2>
                    <p>Nosso horario de atendimento é:</p>
                    <p>De <strong>Segunda-feira</strong> á <strong>Sexta-feira</strong>
                    <strong>Das 08:00</strong> até as <strong>18:00</strong></p>
                </article>
            </div>
        </section>
{% include 'footer.phtml'%}