{% include 'header.phtml'%}
        <section class="sobre row">
            <article class="col-xs-12 col-md-6">
                <h1>Sobre a Aguillar Arts</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                </p>
            </article>
        </section>
        <section class="servicos row container">
            <div class="menu">
                <ul>
                    <li class="disable" id="producao"><img src="./Public/Assets/dist/css/img/icons/producao.png" alt=""></l>
                    <li class="disable" id="email"><img src="./Public/Assets/dist/css/img/icons/email.png" alt=""></l>
                    <li class="disable" id="midia"><img src="./Public/Assets/dist/css/img/icons/midia.png" alt=""></l>
                    <li class="disable" id="criacao"><img src="./Public/Assets/dist/css/img/icons/criacao.png" alt=""></l>
                    <li class="disable" id="visual"><img src="./Public/Assets/dist/css/img/icons/visual.png" alt=""></l>
                    <li class="disable" id="offiline"><img src="./Public/Assets/dist/css/img/icons/offiline.png" alt=""></li>
                </ul>
            </div>
            <div class="texto producao">
                <h2>Produção de Campanhas</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
            <div class="texto email">
                <h2>Email Marketing</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
            <div class="texto midia">
                <h2>Mídias Sociais</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
            <div class="texto criacao">
                <h2>Criação de Site</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
            <div class="texto visual">
                <h2>Identidade Visual</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
            <div class="texto offiline">
                <h2>Mídia Offiline</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto officiis, eum magnam cupiditate ipsa sit illo. Laboriosam, blanditiis, veniam aliquid autem dolore, hic repellendus optio quae vitae dolor dolores. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque nobis, perspiciatis at voluptate enim nihil blanditiis, impedit unde, quis quia autem maxime saepe eligendi ab. Aliquid placeat tempora numquam libero? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sint ut voluptatum quibusdam provident natus. Ducimus corrupti numquam, tempore commodi itaque perspiciatis nobis minima ullam. Accusamus ullam voluptatum, laboriosam repudiandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, sapiente, maiores eos eveniet quas exercitationem fuga sed! Dolores fuga cupiditate veniam eos unde, repudiandae laboriosam aut dolor. Qui, aut, aspernatur.</p>
            </div>
        </section>
        <section class="blog row">
            <h1>Em construção...</h1>
            <p>Em breve muitos artigos para melhorar a projeção da sua empresa na web e nos meios em que atua.</p>
        </section>
        <section class="contato row">
            <div class="container">
                <h1><i class="fa fa-comments-o" aria-hidden="true"></i>Contato</h1>

                <article class="col-xs-12 col-md-3 telefone">

                    <h2><i class="fa fa-phone-square" aria-hidden="true"></i>Telefones</h2>

                    <p>Entre em contato, vamos achar a melhor solução para o seu problema.</p>

                    <a href="tel:1639196840"  target="_blank"><i class="fa fa-phone" aria-hidden="true"></i> (16) 39196840</a><br>                    

                    <a href="tel:16988243540"  target="_blank"><i class="fa fa-mobile" aria-hidden="true"></i> (16) 98824-3540</a><br>

                    <a href="intent://send/16988243540#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end" target="_blank"><i class="fa fa-whatsapp" aria-hidden="true"></i> (16) 98824-3540</a><br>

                </article>

                <article class="col-xs-12 col-md-3 col-md-offset-1 email">

                    <h2><i class="fa fa-envelope" aria-hidden="true"></i>E-mail</h2>

                    <p>Nos envie um email com as suas duvidas, vamos adorar esclarecer. Aceitamos <b>Orçamento</b> tambem.</p>

                    <a href="/contato/">Contato</a>

                </article>

                <article class="col-xs-12 col-md-3 col-md-offset-1 atendimento">

                </article>
            </div>
        </section>
{% include 'footer.phtml'%}