{% include 'header.phtml'%}
        <section class="sobre row">
            <article class="col-xs-12 col-md-6">
                <h1>Sobre a Aguillar Arts</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Harum at unde, accusantium impedit repellat molestias
                    vero nemo a qui nesciunt rem quam, libero perspiciatis
                    expedita ut fugiat odit, porro. Perspiciatis.
                </p>
            </article>
        </section>
        <section class="servicos row">
            <div class="row">
                <article class="col-xs-10 col-md-3">
                    <div class="icons">
                        <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        <i class="fa fa-google-plus-official" aria-hidden="true"></i>
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                        <i class="fa fa-twitter-square" aria-hidden="true"></i>
                    </div>
                </article>
                <article class="col-xs-10 col-md-3">

                </article>
                <article class="col-xs-10 col-md-3">
                </article>
            </div>
            <div class="row">
                <article class="col-xs-10 col-md-3">

                </article>
                <article class="col-xs-10 col-md-3">

                </article>
                <article class="col-xs-10 col-md-3">

                </article>
            </div>
        </section>
{% include 'footer.phtml'%}
